name: Build - Windows

on:
  push:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: Silverlan/pragma/.github/workflows/build-module.yml@main
    if: github.repository != 'Silverlan/pr_module_template'
    with:
      repository: '${{ github.repository }}'
      os: windows
      build-args: '--module pr_source --access-token-mediapipe-wrapper=BUILD_TOKEN1'
    secrets:
      repository_token: ${{ secrets.GITHUB_TOKEN }}
      build_token1: ${{ secrets.UTIL_FGD_TOKEN }}
    permissions:
      contents: write
