name: Build - Linux

on:
  push:
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: write

jobs:
  call-workflow:
    uses: Silverlan/pragma/.github/workflows/build-module.yml@main
    if: github.repository != 'Silverlan/pr_module_template'
    with:
      repository: 'Silverlan/pr_source'
      os: linux
      build-args: '--module pr_mount_external --access-token-fgd=BUILD_TOKEN1'
    secrets:
      repository_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      build_token1: ${{ secrets.UTIL_FGD_TOKEN }}
    permissions:
      contents: write
